### ISSUE TITLE
 RTD10k.h: No such file or directory

### ISSUE THREAD

**Issue by he77PC011** [NitrofMtl/RTD10k-temp-sensor#1]
RTD10k_exemple:42:10: fatal error: RTD10k.h: No such file or directory
 #include <RTD10k.h>
          ^~~~~~~~~~
compilation terminated.
exit status 1
RTD10k.h: No such file or directory
 Arduino IDE  esp32

**Comment by NitrofMtl** [comment]
Typo in the include directive: change k for K
`
#include <RTD10K.h>
`

Or update the library, it have been fix in the example on version  2.1.

Regards.

Nitrof
